#!/usr/bin/env node
// Generates src/version.ts from package.json's version field.
// Runs as a prebuild/pretest step so VERSION is a build-time constant
// instead of a runtime path-relative package.json read.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const contents = `// Generated by scripts/gen-version.mjs — do not edit by hand.
export const VERSION = ${JSON.stringify(pkg.version)};
`;

writeFileSync(join(root, 'src', 'version.ts'), contents);
console.log(`src/version.ts ← ${pkg.version}`);
