#!/usr/bin/env node
// Generates src/version.ts from package.json's version field.
// Runs as a predev/prebuild/pretest step so VERSION is a build-time constant
// instead of a runtime path-relative package.json read.
//
// Idempotent: if src/version.ts already matches the current package.json
// version, the file is left alone — running build/test won't dirty the
// working tree unless the version actually changed.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const outPath = join(root, 'src', 'version.ts');
const nextContents = `// Generated by scripts/gen-version.mjs — do not edit by hand.
export const VERSION = ${JSON.stringify(pkg.version)};
`;

const existing = existsSync(outPath) ? readFileSync(outPath, 'utf-8') : '';
if (existing === nextContents) {
  console.log(`src/version.ts ok (${pkg.version}) — no write`);
} else {
  writeFileSync(outPath, nextContents);
  console.log(`src/version.ts ← ${pkg.version}`);
}
